
import { Country, Language, IncomeRange } from './types';

// ==========================================
// APP CONFIGURATION & TRANSLATIONS
// ==========================================

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'bn', name: 'বাংলা', flag: '🇧🇩' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
];

export const TRANSLATIONS: Record<string, any> = {
  en: {
    selectRegion: "Select your Region",
    regionDesc: "We've organized data for regions around the world. Select a country to see tailored income brackets.",
    searchPlaceholder: "Search country...",
    noResults: "No countries found matching",
    regions: { Asia: "Asia", Europe: "Europe", Americas: "Americas", Oceania: "Oceania", Africa: "Africa" },
    incomeTitle: "Monthly Income for",
    incomeDesc: "Select your approximate monthly income range in",
    back: "Back",
    loading: "Analyzing Local Economy...",
    loadingDesc: "Gathering data for",
    errorTitle: "Analysis Failed",
    tryAgain: "Try Again",
    startOver: "Start Over",
    allocation: "Allocation",
    smartMoves: "Smart Moves for",
    investmentFocus: "Investment Focus",
    monthlyBlueprint: "Monthly Blueprint",
    estIncome: "Est. Net Income",
    edition: "Edition",
    unemployed: "Unemployed / No Income",
    idealAllocation: "Ideal Budget Allocation",
    lifeGoal: "Your Financial Life Goal"
  },
  es: {
    selectRegion: "Selecciona tu Región",
    regionDesc: "Hemos organizado datos de regiones de todo el mundo. Selecciona un país.",
    searchPlaceholder: "Buscar país...",
    noResults: "No se encontraron países",
    regions: { Asia: "Asia", Europe: "Europa", Americas: "Américas", Oceania: "Oceanía", Africa: "África" },
    incomeTitle: "Ingreso Mensual para",
    incomeDesc: "Selecciona tu rango de ingresos mensual aproximado en",
    back: "Atrás",
    loading: "Analizando Economía Local...",
    loadingDesc: "Recopilando datos para",
    errorTitle: "Análisis Fallido",
    tryAgain: "Intentar de nuevo",
    startOver: "Empezar de nuevo",
    allocation: "Asignación",
    smartMoves: "Movimientos Inteligentes para",
    investmentFocus: "Enfoque de Inversión",
    monthlyBlueprint: "Plan Mensual",
    estIncome: "Ingreso Neto Est.",
    edition: "Edición",
    unemployed: "Desempleado / Sin Ingresos",
    idealAllocation: "Asignación de Presupuesto Ideal",
    lifeGoal: "Tu Meta Financiera"
  },
  fr: {
    selectRegion: "Sélectionnez votre Région",
    regionDesc: "Données organisées par régions. Sélectionnez un pays pour voir les tranches.",
    searchPlaceholder: "Rechercher un pays...",
    noResults: "Aucun pays trouvé",
    regions: { Asia: "Asie", Europe: "Europe", Americas: "Amériques", Oceania: "Océanie", Africa: "Afrique" },
    incomeTitle: "Revenu Mensuel pour",
    incomeDesc: "Sélectionnez votre fourchette de revenus mensuels approximative en",
    back: "Retour",
    loading: "Analyse de l'économie locale...",
    loadingDesc: "Collecte de données pour",
    errorTitle: "Échec de l'analyse",
    tryAgain: "Réessayer",
    startOver: "Recommencer",
    allocation: "Allocation",
    smartMoves: "Conseils futés pour",
    investmentFocus: "Focus Investissement",
    monthlyBlueprint: "Plan Mensuel",
    estIncome: "Revenu Net Est.",
    edition: "Édition",
    unemployed: "Chômeur / Pas de revenu",
    idealAllocation: "Allocation Budgétaire Idéale",
    lifeGoal: "Votre Objectif Financier"
  },
  de: {
    selectRegion: "Wählen Sie Ihre Region",
    regionDesc: "Daten nach Regionen organisiert. Wählen Sie ein Land.",
    searchPlaceholder: "Land suchen...",
    noResults: "Keine Länder gefunden",
    regions: { Asia: "Asien", Europe: "Europa", Americas: "Amerika", Oceania: "Ozeanien", Africa: "Afrika" },
    incomeTitle: "Monatliches Einkommen für",
    incomeDesc: "Wählen Sie Ihren ungefähren monatlichen Einkommensbereich in",
    back: "Zurück",
    loading: "Analysiere lokale Wirtschaft...",
    loadingDesc: "Sammle Daten für",
    errorTitle: "Analyse fehlgeschlagen",
    tryAgain: "Erneut versuchen",
    startOver: "Neu starten",
    allocation: "Verteilung",
    smartMoves: "Kluge Schritte für",
    investmentFocus: "Investitionsfokus",
    monthlyBlueprint: "Monatsplan",
    estIncome: "Gesch. Nettoeinkommen",
    edition: "Ausgabe",
    unemployed: "Arbeitslos / Kein Einkommen",
    idealAllocation: "Ideale Budgetverteilung",
    lifeGoal: "Ihr Finanzielles Lebensziel"
  },
  pt: {
    selectRegion: "Selecione sua Região",
    regionDesc: "Dados organizados por regiões. Selecione um país.",
    searchPlaceholder: "Pesquisar país...",
    noResults: "Nenhum país encontrado",
    regions: { Asia: "Ásia", Europe: "Europa", Americas: "Américas", Oceania: "Oceania", Africa: "África" },
    incomeTitle: "Renda Mensal para",
    incomeDesc: "Selecione sua faixa de renda mensal aproximada em",
    back: "Voltar",
    loading: "Analisando Economia Local...",
    loadingDesc: "Coletando dados para",
    errorTitle: "Falha na Análise",
    tryAgain: "Tentar Novamente",
    startOver: "Recomeçar",
    allocation: "Alocação",
    smartMoves: "Dicas Inteligentes para",
    investmentFocus: "Foco em Investimentos",
    monthlyBlueprint: "Plano Mensal",
    estIncome: "Renda Líq. Est.",
    edition: "Edição",
    unemployed: "Desempregado / Sem Renda",
    idealAllocation: "Alocação Ideal do Orçamento",
    lifeGoal: "Seu Objetivo Financeiro"
  },
  bn: {
    selectRegion: "আপনার অঞ্চল নির্বাচন করুন",
    regionDesc: "আমরা বিশ্বজুড়ে অঞ্চলের জন্য ডেটা সাজিয়েছি। উপযুক্ত আয়ের বন্ধনী দেখতে একটি দেশ নির্বাচন করুন।",
    searchPlaceholder: "দেশ অনুসন্ধান করুন...",
    noResults: "কোন দেশ পাওয়া যায়নি",
    regions: { Asia: "এশিয়া", Europe: "ইউরোপ", Americas: "আমেরিকা", Oceania: "ওশেনিয়া", Africa: "আফ্রিকা" },
    incomeTitle: "মাসিক আয়",
    incomeDesc: "আপনার আনুমানিক মাসিক আয়ের সীমা নির্বাচন করুন",
    back: "ফিরে যান",
    loading: "স্থানীয় অর্থনীতি বিশ্লেষণ করা হচ্ছে...",
    loadingDesc: "ডেটা সংগ্রহ করা হচ্ছে",
    errorTitle: "বিশ্লেষণ ব্যর্থ হয়েছে",
    tryAgain: "আবার চেষ্টা করুন",
    startOver: "নতুন করে শুরু করুন",
    allocation: "বন্টন",
    smartMoves: "স্মার্ট পরামর্শ",
    investmentFocus: "বিনিয়োগের লক্ষ্য",
    monthlyBlueprint: "মাসিক ব্লুপ্রিন্ট",
    estIncome: "আনুমানিক নিট আয়",
    edition: "সংস্করণ",
    unemployed: "বেকার / কোনো আয় নেই",
    idealAllocation: "আদর্শ বাজেট বন্টন",
    lifeGoal: "আপনার আর্থিক জীবনের লক্ষ্য"
  },
  hi: {
    selectRegion: "अपना क्षेत्र चुनें",
    regionDesc: "हमने दुनिया भर के क्षेत्रों के लिए डेटा व्यवस्थित किया है। देश चुनें।",
    searchPlaceholder: "देश खोजें...",
    noResults: "कोई देश नहीं मिला",
    regions: { Asia: "एशिया", Europe: "यूरोप", Americas: "अमेरिका", Oceania: "ओशिनिया", Africa: "अफ्रीका" },
    incomeTitle: "मासिक आय",
    incomeDesc: "अपनी अनुमानित मासिक आय सीमा चुनें",
    back: "वापस",
    loading: "स्थानीय अर्थव्यवस्था का विश्लेषण...",
    loadingDesc: "डेटा एकत्र कर रहा है",
    errorTitle: "विश्लेषण विफल",
    tryAgain: "पुनः प्रयास करें",
    startOver: "फिर से शुरू करें",
    allocation: "आवंटन",
    smartMoves: "स्मार्ट सुझाव",
    investmentFocus: "निवेश फोकस",
    monthlyBlueprint: "मासिक खाका",
    estIncome: "अनुमानित शुद्ध आय",
    edition: "संस्करण",
    unemployed: "बेरोजगार / कोई आय नहीं",
    idealAllocation: "आदर्श बजट आवंटन",
    lifeGoal: "आपका वित्तीय जीवन लक्ष्य"
  },
  zh: {
    selectRegion: "选择您的地区",
    regionDesc: "我们整理了世界各地的区域数据。选择一个国家以查看定制的收入等级。",
    searchPlaceholder: "搜索国家...",
    noResults: "未找到匹配的国家",
    regions: { Asia: "亚洲", Europe: "欧洲", Americas: "美洲", Oceania: "大洋洲", Africa: "非洲" },
    incomeTitle: "月收入",
    incomeDesc: "选择您的大致月收入范围（货币单位：",
    back: "返回",
    loading: "正在分析当地经济...",
    loadingDesc: "正在收集数据：",
    errorTitle: "分析失败",
    tryAgain: "重试",
    startOver: "重新开始",
    allocation: "分配",
    smartMoves: "明智举措：",
    investmentFocus: "投资重点",
    monthlyBlueprint: "月度蓝图",
    estIncome: "预估净收入",
    edition: "版",
    unemployed: "失业 / 无收入",
    idealAllocation: "理想预算分配",
    lifeGoal: "您的财务生活目标"
  },
  ar: {
    selectRegion: "اختر منطقتك",
    regionDesc: "لقد قمنا بتنظيم البيانات للمناطق حول العالم. اختر دولة لرؤية فئات الدخل المخصصة.",
    searchPlaceholder: "بحث عن دولة...",
    noResults: "لم يتم العثور على دول",
    regions: { Asia: "آسيا", Europe: "أوروبا", Americas: "الأمريكتان", Oceania: "أوقيانوسيا", Africa: "أفريقيا" },
    incomeTitle: "الدخل الشهري لـ",
    incomeDesc: "حدد نطاق دخلك الشهري التقريبي بـ",
    back: "رجوع",
    loading: "تحليل الاقتصاد المحلي...",
    loadingDesc: "جاري جمع البيانات لـ",
    errorTitle: "فشل التحليل",
    tryAgain: "حاول مرة أخرى",
    startOver: "البدء من جديد",
    allocation: "التخصيص",
    smartMoves: "خطوات ذكية لـ",
    investmentFocus: "التركيز الاستثماري",
    monthlyBlueprint: "المخطط الشهري",
    estIncome: "صافي الدخل التقديري",
    edition: "إصدار",
    unemployed: "عاطل عن العمل / لا دخل",
    idealAllocation: "تخصيص الميزانية المثالي",
    lifeGoal: "هدفك المالي في الحياة"
  },
  ja: {
    selectRegion: "地域を選択",
    regionDesc: "世界中の地域のデータを整理しました。国を選択してください。",
    searchPlaceholder: "国を検索...",
    noResults: "国が見つかりません",
    regions: { Asia: "アジア", Europe: "ヨーロッパ", Americas: "アメリカ", Oceania: "オセアニア", Africa: "アフリカ" },
    incomeTitle: "月収：",
    incomeDesc: "おおよその月収範囲を選択してください（単位：",
    back: "戻る",
    loading: "地域経済を分析中...",
    loadingDesc: "データを収集中：",
    errorTitle: "分析に失敗しました",
    tryAgain: "再試行",
    startOver: "やり直す",
    allocation: "配分",
    smartMoves: "賢い選択：",
    investmentFocus: "投資フォーカス",
    monthlyBlueprint: "月次計画",
    estIncome: "推定純収入",
    edition: "版",
    unemployed: "無職 / 収入なし",
    idealAllocation: "理想的な予算配分",
    lifeGoal: "あなたの経済的目標"
  },
  ru: {
    selectRegion: "Выберите ваш регион",
    regionDesc: "Мы систематизировали данные по регионам мира. Выберите страну.",
    searchPlaceholder: "Поиск страны...",
    noResults: "Страны не найдены",
    regions: { Asia: "Азия", Europe: "Европа", Americas: "Америка", Oceania: "Океания", Africa: "Африка" },
    incomeTitle: "Ежемесячный доход для",
    incomeDesc: "Выберите примерный диапазон ежемесячного дохода в",
    back: "Назад",
    loading: "Анализ местной экономики...",
    loadingDesc: "Сбор данных для",
    errorTitle: "Ошибка анализа",
    tryAgain: "Попробовать снова",
    startOver: "Начать заново",
    allocation: "Распределение",
    smartMoves: "Умные шаги для",
    investmentFocus: "Инвестиционный фокус",
    monthlyBlueprint: "Ежемесячный план",
    estIncome: "Оц. чистый доход",
    edition: "Издание",
    unemployed: "Безработный / Нет дохода",
    idealAllocation: "Идеальное распределение бюджета",
    lifeGoal: "Ваша финансовая цель"
  },
};

// ==========================================
// COUNTRY DATABASE (EDITABLE)
// ==========================================
// HOW TO ADD A COUNTRY:
// 1. Add an object to the list below.
// 2. 'baseScale' determines the starting income range (approx low-middle income).
// 3. Ensure 'code' matches 2-letter ISO code (used for flags).
// 4. 'region' groups it in the UI.

export const COUNTRIES: Country[] = [
  // --- ASIA ---
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', currencyCode: 'BDT', currencySymbol: '৳', region: 'Asia', baseScale: 15000 },
  { code: 'IN', name: 'India', flag: '🇮🇳', currencyCode: 'INR', currencySymbol: '₹', region: 'Asia', baseScale: 20000 },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', currencyCode: 'PKR', currencySymbol: '₨', region: 'Asia', baseScale: 40000 },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', currencyCode: 'LKR', currencySymbol: 'Rs', region: 'Asia', baseScale: 60000 },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵', currencyCode: 'NPR', currencySymbol: 'Rs', region: 'Asia', baseScale: 25000 },
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', currencyCode: 'AFN', currencySymbol: '؋', region: 'Asia', baseScale: 12000 },
  { code: 'CN', name: 'China', flag: '🇨🇳', currencyCode: 'CNY', currencySymbol: '¥', region: 'Asia', baseScale: 4000 },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', currencyCode: 'JPY', currencySymbol: '¥', region: 'Asia', baseScale: 200000 },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', currencyCode: 'KRW', currencySymbol: '₩', region: 'Asia', baseScale: 2200000 },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼', currencyCode: 'TWD', currencySymbol: 'NT$', region: 'Asia', baseScale: 32000 },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', currencyCode: 'HKD', currencySymbol: 'HK$', region: 'Asia', baseScale: 16000 },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', currencyCode: 'IDR', currencySymbol: 'Rp', region: 'Asia', baseScale: 4000000 },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', currencyCode: 'VND', currencySymbol: '₫', region: 'Asia', baseScale: 7000000 },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', currencyCode: 'THB', currencySymbol: '฿', region: 'Asia', baseScale: 15000 },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', currencyCode: 'PHP', currencySymbol: '₱', region: 'Asia', baseScale: 18000 },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', currencyCode: 'MYR', currencySymbol: 'RM', region: 'Asia', baseScale: 2500 },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', currencyCode: 'SGD', currencySymbol: 'S$', region: 'Asia', baseScale: 2500 },
  { code: 'AE', name: 'UAE', flag: '🇦🇪', currencyCode: 'AED', currencySymbol: 'د.إ', region: 'Asia', baseScale: 4000 },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', currencyCode: 'SAR', currencySymbol: '﷼', region: 'Asia', baseScale: 4000 },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', currencyCode: 'QAR', currencySymbol: '﷼', region: 'Asia', baseScale: 4500 },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', currencyCode: 'KWD', currencySymbol: 'KD', region: 'Asia', baseScale: 350 },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', currencyCode: 'BHD', currencySymbol: 'BD', region: 'Asia', baseScale: 400 },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', currencyCode: 'OMR', currencySymbol: '﷼', region: 'Asia', baseScale: 400 },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', currencyCode: 'TRY', currencySymbol: '₺', region: 'Asia', baseScale: 17000 },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', currencyCode: 'KZT', currencySymbol: '₸', region: 'Asia', baseScale: 180000 },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', currencyCode: 'UZS', currencySymbol: 'лв', region: 'Asia', baseScale: 2500000 },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', currencyCode: 'IRR', currencySymbol: '﷼', region: 'Asia', baseScale: 60000000 },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', currencyCode: 'IQD', currencySymbol: 'ع.د', region: 'Asia', baseScale: 600000 },

  // --- EUROPE ---
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', currencyCode: 'GBP', currencySymbol: '£', region: 'Europe', baseScale: 1400 },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1600 },
  { code: 'FR', name: 'France', flag: '🇫🇷', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1400 },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1200 },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1100 },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1800 },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', currencyCode: 'CHF', currencySymbol: 'CHF', region: 'Europe', baseScale: 3500 },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', currencyCode: 'SEK', currencySymbol: 'kr', region: 'Europe', baseScale: 20000 },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', currencyCode: 'NOK', currencySymbol: 'kr', region: 'Europe', baseScale: 22000 },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', currencyCode: 'DKK', currencySymbol: 'kr', region: 'Europe', baseScale: 15000 },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1600 },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1800 },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1600 },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1600 },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 900 },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 850 },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', currencyCode: 'PLN', currencySymbol: 'zł', region: 'Europe', baseScale: 3500 },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', currencyCode: 'CZK', currencySymbol: 'Kč', region: 'Europe', baseScale: 22000 },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', currencyCode: 'HUF', currencySymbol: 'Ft', region: 'Europe', baseScale: 300000 },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', currencyCode: 'RON', currencySymbol: 'lei', region: 'Europe', baseScale: 3000 },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', currencyCode: 'UAH', currencySymbol: '₴', region: 'Europe', baseScale: 15000 },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', currencyCode: 'RUB', currencySymbol: '₽', region: 'Europe', baseScale: 45000 },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾', currencyCode: 'BYN', currencySymbol: 'Br', region: 'Europe', baseScale: 1200 },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', currencyCode: 'RSD', currencySymbol: 'дин', region: 'Europe', baseScale: 70000 },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1000 },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', currencyCode: 'BGN', currencySymbol: 'лв', region: 'Europe', baseScale: 1400 },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1000 },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1200 },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1100 },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1100 },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', currencyCode: 'EUR', currencySymbol: '€', region: 'Europe', baseScale: 1200 },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸', currencyCode: 'ISK', currencySymbol: 'kr', region: 'Europe', baseScale: 350000 },
  { code: 'AL', name: 'Albania', flag: '🇦🇱', currencyCode: 'ALL', currencySymbol: 'L', region: 'Europe', baseScale: 50000 },
  { code: 'BA', name: 'Bosnia & Herzegovina', flag: '🇧🇦', currencyCode: 'BAM', currencySymbol: 'KM', region: 'Europe', baseScale: 1000 },

  // --- NORTH AMERICA ---
  { code: 'US', name: 'United States', flag: '🇺🇸', currencyCode: 'USD', currencySymbol: '$', region: 'Americas', baseScale: 2500 },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', currencyCode: 'CAD', currencySymbol: 'C$', region: 'Americas', baseScale: 2500 },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', currencyCode: 'MXN', currencySymbol: 'Mex$', region: 'Americas', baseScale: 12000 },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', currencyCode: 'GTQ', currencySymbol: 'Q', region: 'Americas', baseScale: 3500 },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', currencyCode: 'CRC', currencySymbol: '₡', region: 'Americas', baseScale: 350000 },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', currencyCode: 'PAB', currencySymbol: 'B/.', region: 'Americas', baseScale: 700 },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', currencyCode: 'DOP', currencySymbol: 'RD$', region: 'Americas', baseScale: 25000 },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲', currencyCode: 'JMD', currencySymbol: 'J$', region: 'Americas', baseScale: 60000 },

  // --- SOUTH AMERICA ---
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', currencyCode: 'BRL', currencySymbol: 'R$', region: 'Americas', baseScale: 2800 },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', currencyCode: 'ARS', currencySymbol: '$', region: 'Americas', baseScale: 200000 },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', currencyCode: 'COP', currencySymbol: '$', region: 'Americas', baseScale: 1800000 },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', currencyCode: 'CLP', currencySymbol: '$', region: 'Americas', baseScale: 550000 },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', currencyCode: 'PEN', currencySymbol: 'S/', region: 'Americas', baseScale: 1800 },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', currencyCode: 'VES', currencySymbol: 'Bs.', region: 'Americas', baseScale: 4000 },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', currencyCode: 'USD', currencySymbol: '$', region: 'Americas', baseScale: 450 },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', currencyCode: 'BOB', currencySymbol: 'Bs.', region: 'Americas', baseScale: 2800 },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', currencyCode: 'UYU', currencySymbol: '$U', region: 'Americas', baseScale: 30000 },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', currencyCode: 'PYG', currencySymbol: '₲', region: 'Americas', baseScale: 3000000 },

  // --- OCEANIA ---
  { code: 'AU', name: 'Australia', flag: '🇦🇺', currencyCode: 'AUD', currencySymbol: 'A$', region: 'Oceania', baseScale: 3500 },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', currencyCode: 'NZD', currencySymbol: 'NZ$', region: 'Oceania', baseScale: 3500 },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', currencyCode: 'FJD', currencySymbol: 'FJ$', region: 'Oceania', baseScale: 1200 },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', currencyCode: 'PGK', currencySymbol: 'K', region: 'Oceania', baseScale: 2000 },

  // --- AFRICA ---
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', currencyCode: 'EGP', currencySymbol: 'E£', region: 'Africa', baseScale: 6000 },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', currencyCode: 'ZAR', currencySymbol: 'R', region: 'Africa', baseScale: 8000 },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', currencyCode: 'NGN', currencySymbol: '₦', region: 'Africa', baseScale: 80000 },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', currencyCode: 'KES', currencySymbol: 'KSh', region: 'Africa', baseScale: 20000 },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', currencyCode: 'MAD', currencySymbol: 'DH', region: 'Africa', baseScale: 3500 },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', currencyCode: 'GHS', currencySymbol: 'GH₵', region: 'Africa', baseScale: 2500 },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', currencyCode: 'ETB', currencySymbol: 'Br', region: 'Africa', baseScale: 5000 },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', currencyCode: 'TZS', currencySymbol: 'TSh', region: 'Africa', baseScale: 400000 },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', currencyCode: 'UGX', currencySymbol: 'USh', region: 'Africa', baseScale: 600000 },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', currencyCode: 'DZD', currencySymbol: 'DA', region: 'Africa', baseScale: 25000 },
];

// Helper function for Income Selector
export const getIncomeRanges = (country: Country, language: string = 'en'): IncomeRange[] => {
  const t = TRANSLATIONS[language] || TRANSLATIONS['en'];
  const scale = country.baseScale;
  const currency = country.currencySymbol;
  const fmt = (n: number) => n.toLocaleString();

  return [
    { min: 0, max: 0, label: t.unemployed }, // 0 / Unemployed
    { min: 1, max: scale, label: `${currency}1 - ${currency}${fmt(scale)}` }, // 1 to Scale (Starting)
    { min: scale, max: scale * 2, label: `${currency}${fmt(scale)} - ${currency}${fmt(scale * 2)}` },
    { min: scale * 2, max: scale * 4, label: `${currency}${fmt(scale * 2)} - ${currency}${fmt(scale * 4)}` },
    { min: scale * 4, max: scale * 8, label: `${currency}${fmt(scale * 4)} - ${currency}${fmt(scale * 8)}` },
    { min: scale * 8, max: scale * 15, label: `${currency}${fmt(scale * 8)} - ${currency}${fmt(scale * 15)}` },
    { min: scale * 15, max: null, label: `${currency}${fmt(scale * 15)}+` },
  ];
};
